= Legal and Disclaimers

== License

*Agile Android Software Development* by Etienne Savard is licensed under a http://creativecommons.org/licenses/by-nc/4.0[Creative Commons Attribution-NonCommercial 4.0 International License].

For commercial use of this book, please contact the author for inquiries (see the book website for contact information): http://agiledroid.com

== How to support this book

=== Donations

This book is free (as in free speech, not free beer).  http://bit.ly/1tKb4y1[Donations are welcome], and a great way to show your support for my work.  All donators will be credited in the acknowledgments section of this book. You can give any amount you like.

=== Opinions

Please share your opinions and comments about the book by answering this short survey: http://goo.gl/4xosAm

=== Referral Links

In the electronic versions of this book (pdf, mobi, epub, etc.), you will find referral links in the text. These links allow the author to get paid if you end up buying the products to which they refer. At any time, you can decide to copy the link text in your web browser rather than clicking the referral links.

== Limited Warranty

Symbiosoft warrants that the ebook files are free from defects in the operational sense that they can be read by a PDF Reader, ePub reader, Kindle, or other. EXCEPT FOR THIS EXPRESS LIMITED WARRANTY, SYMBIOSOFT MAKES AND YOU RECEIVE NO WARRANTIES, EXPRESS, IMPLIED, STATUTORY OR IN ANY COMMUNICATION WITH YOU, AND SYMBIOSOFT SPECIFICALLY DISCLAIMS ANY OTHER WARRANTY INCLUDING THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS OR A PARTICULAR PURPOSE. SYMBIOSOFT DOES NOT WARRANT THAT THE OPERATION OF THE EBOOK WILL BE UNINTERRUPTED OR ERROR FREE. If the ebook was purchased in the United States, the above exclusions may not apply to you as some states do not allow the exclusion of implied warranties. In addition to the above warranty rights, you may also have other rights that vary from state to state.


== Limitation of Liability

IN NO EVENT WILL SYMBIOSOFT BE LIABLE FOR ANY DAMAGES, WHETHER ARISING FOR TORT OR CONTRACT, INCLUDING LOSS OF DATA, LOST PROFITS, OR OTHER SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR INDIRECT DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE EBOOK.


== Trademarks Disclaimer

Symbiosoft logo and name are trademarks of Symbiosoft (9250-2780 QUEBEC INC.).

Product names, logos, brands and other trademarks referred to within this work are the property of their respective trademark holders. These trademark holders are not affiliated with Symbiosoft, our products, or our websites. They do not sponsor or endorse our materials.  Below is a partial listing of these trademarks and their owners.  This list is subject to change without notice.

Android is a trademark of Google Inc.  Portions are modifications based on work created and shared by Google and used according to terms described in the Creative Commons 3.0 Attribution License.

Opinions expressed in this eBook are those of Etienne Savard, and may not be shared by Symbiosoft's customers.